baseURL = "http://jovi.io/"
languageCode = "zh-cn"
title = "jovi's blog"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[params]
  author = "Jovi mao"
  hello = "Hi,I'm Jovi"
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  github = "https://github.com/maojiawei"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/banner.jpg"
