baseurl = "http://jovi.io/"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh-cn"
title = "Jovi's blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
#googleAnalytics = "XXX"

[taxonomies]
  category = "categories"
  tag = "tags"

[Params]
  hello = "Hi,I'm Jovi"
  subtitle = "Welcome to IT world"
  favicon = "images/favicon.ico"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"

[[Params.bigimg]]
  src = "img/banner.jpg"
  desc = "Use your keyboard to improve the world"

[Author]
  name = "Jovi mao"
  website = "jovi.io"
  email = "maojiaweix@126.com"
  github = "maojiawei"

[[menu.main]]
    identifier = "container"
    name = "容器云"
    url = "categories/container"
    weight = 1

[[menu.main]]
    identifier = "microservice"
    name = "微服务"
    url = "categories/microservice"
    weight = 1
