baseURL = "http://jovi.io/"
languageCode = "zh-cn"
title = "jovi's blog"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "zh-CN"
googleAnalytics = ""
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "Jovi mao"
  hello = "Welcome to IT world"
  favicon = "images/favicon.ico"
  description = "The last theme you'll ever need. Maybe."
  github = "https://github.com/maojiawei"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "images/banner.jpg"

[[menu.main]]
    identifier = "microservice"
    name = "微服务"
    weight = 1
    url = "/posts/microservice/"

[[menu.main]]
    identifier = "container"
    name = "容器"
    weight = 1
    url = "/posts//container/"